alias dc='docker compose'
alias n='nnn -de'
alias ipy=ipython
alias s='sudo systemctl'
alias r='mise run'
if [ "$PWD" = "$HOME" ]; then cd /srv/apps; fi
HISTSIZE=9999999
HISTFILESIZE=9999999
export RIPGREP_CONFIG_PATH=~/.config/.ripgreprc
python ~/.local/list_services_hosts.py
eval "$(fzf --bash)"
eval "$(starship init bash)"
